[project]
name = "setap-app"
version = "1.0.0"
description = "Server for our setap-app."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"